version: 0.1.0-{build}-beta
pull_requests:  
  do_not_increment_build_number: true
branches:
  only:
  - master
nuget:  
  disable_publish_on_pr: true
skip_tags: true
before_build:
- ps: >-
    (new-object net.webclient).DownloadFile('https://download.microsoft.com/download/B/9/F/B9F1AF57-C14A-4670-9973-CDF47209B5BF/dotnet-dev-win-x64.1.0.4.exe','core.exe')
    
    core.exe /install /quiet /norestart
    
    dotnet --version
build_script:  
- ps: .\Build.ps1
