version: 0.1.0-{build}-beta
pull_requests:  
  do_not_increment_build_number: true
branches:
  only:
  - master
nuget:  
  disable_publish_on_pr: true
skip_tags: true
before_build:
- ps: >-
    (new-object net.webclient).DownloadFile('https://dotnetcli.blob.core.windows.net/dotnet/Sdk/master/dotnet-dev-win-x64.latest.exe','core.exe')
    
    core.exe /install /quiet /norestart
    
    dotnet --version
build_script:  
- ps: .\Build.ps1
